### ISSUE TITLE
An error with gogoapi

### ISSUE THREAD

**Issue by NailouZhang** [toniher/gogoapi#3]
Hi, Toni
Thank you again for your help in installing the correct version of targetP. Here, I met an error with gogoapi.

I'm new to NodeJS and don't know how to fix gagapi with the following command. Could you kindly help me solve my problem？

# install gogoapi
git clone https://github.com/toniher/gogoapi.git
docker build -t mygogoapi:20211205 -f Dockerfile .

# Download (Database dumps for convenience) from https://biocore.crg.eu/gogoapi/biosql-202010.sql.gz
gunzip biosql-202010.sql.gz
mv biosql-202010.sql biosql.sql
sed -i 's/\/biodb/biosql.sql/g'

# Then run
docker run --name mygogoapi -v config.json:/data/config/config.json mygogoapi:20211205
:(, I get the the fellowed errors

warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
(node:8) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
/data/soft/gogoapi/node_modules/nconf/lib/nconf/stores/file.js:170
    throw new Error("Error parsing your configuration file: [" + this.file + ']: ' + ex.message);
    ^

Error: Error parsing your configuration file: [/data/config/config.json]: EISDIR: illegal operation on a directory, read
    at exports.File.File.loadSync (/data/soft/gogoapi/node_modules/nconf/lib/nconf/stores/file.js:170:11)
    at exports.Provider.Provider.add (/data/soft/gogoapi/node_modules/nconf/lib/nconf/provider.js:136:23)
    at exports.Provider.Provider.file (/data/soft/gogoapi/node_modules/nconf/lib/nconf/provider.js:63:15)
    at new config (/data/soft/gogoapi/config.js:9:8)
    at module.exports (/data/soft/gogoapi/config.js:18:9)
    at Object.<anonymous> (/data/soft/gogoapi/index.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
error: Forever detected script exited with code: 1

**Comment by NailouZhang** [comment]
Hi, Toni
When I modify basepath to /data/config/biosql.sql, and then run follow command, I works 
docker run --name mygogoapi -v $PWD/config.json:/data/config/config.json -d mygogoapi:20211205

**Comment by toniher** [comment]
Hi @NailouZhang ! Sorry I didn't get a notification of your message here. I updated a bit the documentation to make it clearer. The problem is that you need to import the SQL dump into an existing MySQL (empty) database. You adapt the database name, user and password in the ```config.json``` file to match it. Hope it helps!
